name: Build Midnight Commander (macOS Intel + DMG)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13   # Intel runner
    steps:
      - name: Get latest release info
        id: get_release
        run: |
          LATEST=$(curl -s https://api.github.com/repos/MidnightCommander/mc/releases/latest | jq -r .tag_name)
          echo "latest_tag=$LATEST" >> $GITHUB_ENV

      - name: Download source tarball
        run: |
          curl -L https://github.com/MidnightCommander/mc/archive/refs/tags/${{ env.latest_tag }}.tar.gz -o mc.tar.gz
          tar -xzf mc.tar.gz
          mv mc-* mc

      - name: Install dependencies
        run: |
          brew update
          brew install gettext pkg-config glib

      - name: Configure
        working-directory: mc
        run: |
          ./configure \
            --prefix=/usr/local \
            CPPFLAGS="-I/usr/local/include" \
            LDFLAGS="-L/usr/local/lib"

      - name: Build
        working-directory: mc
        run: make -j$(sysctl -n hw.ncpu)

      - name: Install into staging dir
        working-directory: mc
        run: |
          mkdir -p ../pkgroot/usr/local
          make install DESTDIR=$PWD/../pkgroot

      - name: Create .pkg
        run: |
          pkgbuild \
            --root pkgroot \
            --identifier org.midnightcommander.mc \
            --version "${{ env.latest_tag }}" \
            mc-macos-intel.pkg

      - name: Create .dmg
        run: |
          mkdir dmgdir
          mv mc-macos-intel.pkg dmgdir/
          hdiutil create -volname "Midnight Commander" -srcfolder dmgdir -ov -format UDZO mc-macos-intel.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mc-macos-intel-dmg
          path: mc-macos-intel.dmg
