name: Build Midnight Commander 4.8.33 (macOS Intel + DMG + SHA256)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13   # Intel runner
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install gettext pkg-config glib jq xz

      - name: Download source tarball and SHA256
        run: |
          curl -L -O https://ftp.osuosl.org/pub/midnightcommander/mc-4.8.33.tar.xz
          curl -L -O https://ftp.osuosl.org/pub/midnightcommander/mc-4.8.33.sha256

      - name: Verify SHA256
        run: shasum -a 256 -c mc-4.8.33.sha256

      - name: Extract source
        run: |
          tar -xf mc-4.8.33.tar.xz
          mv mc-4.8.33 mc

      - name: Configure
        working-directory: mc
        run: |
          ./configure \
            --prefix=/usr/local \
            CPPFLAGS="-I/usr/local/include" \
            LDFLAGS="-L/usr/local/lib"

      - name: Build
        working-directory: mc
        run: make -j$(sysctl -n hw.ncpu)

      - name: Install into staging dir
        working-directory: mc
        run: |
          mkdir -p ../pkgroot/usr/local
          make install DESTDIR=$PWD/../pkgroot

      - name: Create .pkg
        run: |
          pkgbuild \
            --root pkgroot \
            --identifier org.midnightcommander.mc \
            --version "4.8.33" \
            mc-macos-intel.pkg

      - name: Create .dmg
        run: |
          mkdir dmgdir
          mv mc-macos-intel.pkg dmgdir/
          hdiutil create -volname "Midnight Commander" -srcfolder dmgdir -ov -format UDZO mc-4.8.33-macos-intel.dmg

      - name: Compute SHA256 for DMG
        run: shasum -a 256 mc-4.8.33-macos-intel.dmg > mc-4.8.33-macos-intel.dmg.sha256

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mc-macos-intel
          path: |
            mc-4.8.33-macos-intel.dmg
            mc-4.8.33-macos-intel.dmg.sha256
