name: Build Midnight Commander (macOS Intel + DMG)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-13   # Intel runner
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool gettext pkg-config glib

      - name: Bootstrap (generate configure)
        run: autoreconf -fi

      - name: Configure
        run: |
          ./configure \
            --prefix=/usr/local \
            CPPFLAGS="-I/usr/local/include" \
            LDFLAGS="-L/usr/local/lib"

      - name: Build
        run: make -j$(sysctl -n hw.ncpu)

      - name: Install into staging dir
        run: |
          mkdir -p pkgroot/usr/local
          make install DESTDIR=$PWD/pkgroot

      - name: Create .pkg
        run: |
          pkgbuild \
            --root pkgroot \
            --identifier org.midnightcommander.mc \
            --version "$(./src/mc --version | head -n1 | awk '{print $3}')" \
            mc-macos-intel.pkg

      - name: Create .dmg
        run: |
          mkdir dmgdir
          mv mc-macos-intel.pkg dmgdir/
          hdiutil create -volname "Midnight Commander" -srcfolder dmgdir -ov -format UDZO mc-macos-intel.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mc-macos-intel-dmg
          path: mc-macos-intel.dmg
