name: Build Midnight Commander (macOS Intel + DMG + SHA256)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13   # Intel runner
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install gettext pkg-config glib jq

      - name: Get latest release tarball URL
        id: get_release
        run: |
          TARBALL_URL=$(curl -s https://api.github.com/repos/MidnightCommander/mc/releases/latest | jq -r .tarball_url)
          if [ -z "$TARBALL_URL" ] || [ "$TARBALL_URL" = "null" ]; then
            echo "Failed to get latest release tarball URL!"
            exit 1
          fi
          echo "tarball_url=$TARBALL_URL" >> $GITHUB_ENV
          echo "Latest release tarball URL: $TARBALL_URL"

      - name: Download source tarball
        run: |
          curl -L ${{ env.tarball_url }} -o mc.tar.gz
          tar -xzf mc.tar.gz
          mv mc-* mc

      - name: Configure
        working-directory: mc
        run: |
          ./configure \
            --prefix=/usr/local \
            CPPFLAGS="-I/usr/local/include" \
            LDFLAGS="-L/usr/local/lib"

      - name: Build
        working-directory: mc
        run: make -j$(sysctl -n hw.ncpu)

      - name: Install into staging dir
        working-directory: mc
        run: |
          mkdir -p ../pkgroot/usr/local
          make install DESTDIR=$PWD/../pkgroot

      - name: Create .pkg
        run: |
          pkgbuild \
            --root pkgroot \
            --identifier org.midnightcommander.mc \
            --version "latest" \
            mc-macos-intel.pkg

      - name: Create .dmg
        run: |
          mkdir dmgdir
          mv mc-macos-intel.pkg dmgdir/
          hdiutil create -volname "Midnight Commander" -srcfolder dmgdir -ov -format UDZO mc-macos-intel.dmg

      - name: Compute SHA256
        run: |
          echo "SHA256 of mc-macos-intel.dmg:"
          shasum -a 256 mc-macos-intel.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mc-macos-intel-dmg
          path: mc-macos-intel.dmg
