name: Build Midnight Commander with S-Lang (macOS Intel + DMG + SHA256)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      # ------------------------
      # 1. Установка зависимостей
      # ------------------------
      - name: Install dependencies
        run: |
          brew update
          brew install gettext pkg-config glib jq

      # ------------------------
      # 2. Сборка и установка S-Lang
      # ------------------------
      - name: Download and install S-Lang
        run: |
          curl -LO https://www.jedsoft.org/releases/slang/slang-2.3.2.tar.gz
          tar -xzf slang-2.3.2.tar.gz
          cd slang-2.3.2
          ./configure --prefix=/usr/local
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ..
          # Проверим наличие библиотеки
          ls -l /usr/local/lib/libslang.2.dylib

      # ------------------------
      # 3. Скачивание исходников MC
      # ------------------------
      - name: Download Midnight Commander
        run: |
          curl -LO https://ftp.osuosl.org/pub/midnightcommander/mc-4.8.33.tar.bz2
          curl -LO https://ftp.osuosl.org/pub/midnightcommander/mc-4.8.33.sha256

      # ------------------------
      # 4. Проверка SHA256
      # ------------------------
      - name: Verify SHA256
        run: |
          grep "mc-4.8.33.tar.bz2" mc-4.8.33.sha256 | shasum -a 256 -c

      # ------------------------
      # 5. Распаковка исходников MC
      # ------------------------
      - name: Extract source
        run: |
          tar -xjf mc-4.8.33.tar.bz2
          mv mc-4.8.33 mc

      # ------------------------
      # 6. Конфигурация и сборка MC
      # ------------------------
      - name: Configure MC
        working-directory: mc
        run: |
          ./configure \
            --prefix=/usr/local \
            CPPFLAGS="-I/usr/local/include" \
            LDFLAGS="-L/usr/local/lib"

      - name: Build MC
        working-directory: mc
        run: make -j$(sysctl -n hw.ncpu)

      # ------------------------
      # 7. Установка MC в staging dir
      # ------------------------
      - name: Install into staging dir
        working-directory: mc
        run: |
          mkdir -p ../pkgroot/usr/local
          make install DESTDIR=$PWD/../pkgroot

      # ------------------------
      # 8. Создание .pkg
      # ------------------------
      - name: Create .pkg
        run: |
          pkgbuild \
            --root pkgroot \
            --identifier org.midnightcommander.mc \
            --version "4.8.33" \
            mc-macos-intel.pkg

      # ------------------------
      # 9. Создание .dmg
      # ------------------------
      - name: Create .dmg
        run: |
          mkdir dmgdir
          mv mc-macos-intel.pkg dmgdir/
          hdiutil create -volname "Midnight Commander" -srcfolder dmgdir -ov -format UDZO mc-macos-intel.dmg

      # ------------------------
      # 10. SHA256 и загрузка артефакта
      # ------------------------
      - name: Compute SHA256
        run: shasum -a 256 mc-macos-intel.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mc-macos-intel-dmg
          path: mc-macos-intel.dmg
