name: Build Midnight Commander (macOS Intel + DMG + static S-Lang)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install gettext pkg-config glib s-lang bzip2 xz

      - name: Download Midnight Commander source
        run: |
          MC_VER=4.8.33
          curl -LO https://ftp.osuosl.org/pub/midnightcommander/mc-$MC_VER.tar.bz2
          curl -LO https://ftp.osuosl.org/pub/midnightcommander/mc-$MC_VER.sha256
          shasum -a 256 -c mc-$MC_VER.sha256
          tar -xjf mc-$MC_VER.tar.bz2
          mv mc-$MC_VER mc

      - name: Configure with static S-Lang
        working-directory: mc
        run: |
          ./configure \
            --prefix=/usr/local \
            --enable-static \
            --disable-nls \
            --with-slang=system \
            CPPFLAGS="-I/usr/local/include" \
            LDFLAGS="-L/usr/local/lib -static"

      - name: Build
        working-directory: mc
        run: make -j$(sysctl -n hw.ncpu)

      - name: Install into staging dir
        working-directory: mc
        run: |
          mkdir -p ../pkgroot/usr/local
          make install DESTDIR=$PWD/../pkgroot

      - name: Create .pkg
        run: |
          pkgbuild \
            --root pkgroot \
            --identifier org.midnightcommander.mc \
            --version "4.8.33" \
            mc-macos-intel.pkg

      - name: Create .dmg
        run: |
          mkdir dmgdir
          mv mc-macos-intel.pkg dmgdir/
          hdiutil create -volname "Midnight Commander" -srcfolder dmgdir -ov -format UDZO mc-macos-intel.dmg

      - name: Compute SHA256
        run: shasum -a 256 mc-macos-intel.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mc-macos-intel-dmg
          path: mc-macos-intel.dmg
